language: go
go:
  - 1.5
  - tip
env:
  - secure: "Q9wkiPZlZxOnxO9MG0+0OY7Yguuxo0m19EKnYrEdV20vPFr575rE79vdvvzXK3E3wq7cz1MFWFHnCS6jP0yoI5/jwJkqphEQEsL/OkZMXku+Srt9MXrHS/G5Vb+j3gcRhhSMhax478IXbwFHX8kk/rooyZJFyZTOrl38QKVxSTvNhVgC9T73UFIkwUeIYJCrBSis21znn5bEpk4ZGDtofKQuJmHcZ0U0pnHA1mH1wk3YQSyI5yClDtWkDdGU3IYrnHPNhqS4HrbDjeyTo114U320rZzfiuQinJjvwpFQu3YA3qHsU2njrioHbG8TKdyL7zxNhDuZKI11ridKZDNG2p1v8depECsDZspwT6PtTSR3VWKX9UY9Y72V936m0VHcHsJKtl3KrE4b/9Y1Iwru2oe+M3rlBemEFXyOAs/M18lygD3835m32fIT6ZY/ikFHm4xphO1KzJfJvxOJjazIDBglmNqvjQ3zQ/IciQdr9Nu+xMV/km46p3KmdCFnxEFJUHK0TRePrD5arZQb2XspaJfHM9k/s9PdY2feUUTmD80TIENO7Wb9H8JY5ViUdk9DpVPteyIcMgOpEy9wbGH4C3BO6we8qcU6aj8Sc0NOCtT6fkmbcbMNK8iCn+9HI0OLU9Pu5e/n9CDi8Zpz1s2VktqQMrn8ftMIBYwb1fD6QNQ="
services:
  - redis-server
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/garyburd/redigo/redis
  - go get github.com/asaskevich/govalidator
script:
  - REDISURL="redis://localhost:6379/0" go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
